### PR TITLE
3-fix-sync

### LINKED ISSUE #3: Application freezes when LogStash is not available

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #3

### CODE REVIEW

File: logstash-rs/src/buffer.rs [hunk 1]
```diff
@@ -39,18 +41,26 @@ impl BufferedSender {
...
     fn flush(&self) -> Result<()> {
-        self.sender.send(Command::Flush)?;
-        Ok(())
+        let result = self.sender.try_send(Command::Flush);
+        process_result(result)
+    }
+}
+
+fn process_result<T>(r: std::result::Result<(), TrySendError<T>>) -> Result<()> {
+    if matches!(r, Err(TrySendError::Disconnected(..))) {
```
Comment (ikopylov) [inline logstash-rs/src/buffer.rs:60]: I think it is better to return error for overflow case too

Comment (ikopylov) [inline logstash-rs/src/buffer.rs:60]: I think it would be good to return error also on overflow. But to reduce the error intensity (by default log4rs write them to stderr) do that only for messages on Warn level and above

Comment (idruzhitskiy) [reply logstash-rs/src/buffer.rs:61]: Done for either single message or batch with at least one `Warn`

File: logstash-rs/src/buffer.rs [hunk 2]
```diff
@@ -39,18 +41,29 @@ impl BufferedSender {
...
-        Ok(())
+        let result = self.sender.try_send(Command::Flush);
+        process_result(result, false)
+    }
+}
+
+fn process_result<T>(r: std::result::Result<(), TrySendError<T>>, log_full: bool) -> Result<()> {
+    if matches!(r, Err(TrySendError::Disconnected(..))) {
+        return Err(Error::SenderThreadStopped(r.unwrap_err().to_string()));
+    } else if (log_full && matches!(r, Err(TrySendError::Full(..)))) {
```
Comment (ikopylov) [inline logstash-rs/src/buffer.rs:63]: I think, it is better to do a single match, that checks for both `Disconnected` and `Full`

File: logstash-rs/src/buffer.rs [hunk 3]
```diff
@@ -39,18 +41,29 @@ impl BufferedSender {
...
     fn send(&self, event: LogStashRecord) -> Result<()> {
-        self.sender.send(Command::Send(event)).map_err(From::from)
+        let result = self.sender.try_send(Command::Send(event));
+        process_result(result, event.level <= Level::Warn)
     }
 
     fn send_batch(&self, events: Vec<LogStashRecord>) -> Result<()> {
-        self.sender.send(Command::SendBatch(events))?;
-        Ok(())
+        let important = events.iter().any(|e| e.level <= Level::Warn);
```
Comment (ikopylov) [inline logstash-rs/src/buffer.rs:49]: This gives an overhead event when there is no error. You should estimate importance only if error happened (after `try_send`)

Comment (idruzhitskiy) [reply logstash-rs/src/buffer.rs:49]: But events is being moved into command, so it can only be checked before

**Review by ikopylov — APPROVED** [review]
LGTM
